"""Initial college base schema

Revision ID: 1f0fc964eedc
Revises: 
Create Date: 2026-03-26 00:04:13.998739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f0fc964eedc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('college_departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('hod_teacher_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['hod_teacher_id'], ['college_faculty.id'], name='fk_dept_hod', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_college_departments_id'), 'college_departments', ['id'], unique=False)
    op.create_index(op.f('ix_college_departments_name'), 'college_departments', ['name'], unique=True)
    op.create_table('placement_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_placement_companies_id'), 'placement_companies', ['id'], unique=False)
    op.create_table('college_faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('qualification', sa.String(length=255), nullable=True),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['college_departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_college_faculty_employee_id'), 'college_faculty', ['employee_id'], unique=True)
    op.create_index(op.f('ix_college_faculty_id'), 'college_faculty', ['id'], unique=False)
    op.create_index(op.f('ix_college_faculty_user_id'), 'college_faculty', ['user_id'], unique=True)
    op.create_table('college_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('duration_years', sa.Integer(), nullable=True),
    sa.Column('total_credits', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['college_departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_college_programs_id'), 'college_programs', ['id'], unique=False)
    op.create_table('placement_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('eligibility_criteria', sa.Text(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['placement_companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_placement_jobs_id'), 'placement_jobs', ['id'], unique=False)
    op.create_table('college_semesters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['college_programs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_college_semesters_id'), 'college_semesters', ['id'], unique=False)
    op.create_table('hostels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('warden_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['warden_id'], ['college_faculty.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hostels_id'), 'hostels', ['id'], unique=False)
    op.create_table('labs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('in_charge_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['college_departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['in_charge_id'], ['college_faculty.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_labs_id'), 'labs', ['id'], unique=False)
    op.create_table('research_patents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('inventors', sa.Text(), nullable=True),
    sa.Column('patent_number', sa.String(length=100), nullable=True),
    sa.Column('filing_date', sa.DateTime(), nullable=True),
    sa.Column('grant_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['college_faculty.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_patents_id'), 'research_patents', ['id'], unique=False)
    op.create_table('research_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('principal_investigator_id', sa.Integer(), nullable=True),
    sa.Column('co_investigators', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('funding_amount', sa.String(length=100), nullable=True),
    sa.Column('funding_agency', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['principal_investigator_id'], ['college_faculty.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_projects_id'), 'research_projects', ['id'], unique=False)
    op.create_table('research_publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('journal_name', sa.String(length=200), nullable=True),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('volume', sa.String(length=50), nullable=True),
    sa.Column('issue', sa.String(length=50), nullable=True),
    sa.Column('pages', sa.String(length=50), nullable=True),
    sa.Column('doi', sa.String(length=100), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['college_faculty.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_publications_id'), 'research_publications', ['id'], unique=False)
    op.create_table('college_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('semester_id', sa.Integer(), nullable=True),
    sa.Column('instructor_id', sa.Integer(), nullable=True),
    sa.Column('is_elective', sa.Boolean(), nullable=True),
    sa.Column('max_students', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['college_departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instructor_id'], ['college_faculty.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['semester_id'], ['college_semesters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_college_courses_id'), 'college_courses', ['id'], unique=False)
    op.create_table('college_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('roll_number', sa.String(length=50), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('semester_id', sa.Integer(), nullable=True),
    sa.Column('enrollment_date', sa.Date(), nullable=True),
    sa.Column('cgpa', sa.Float(), nullable=True),
    sa.Column('total_credits_completed', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['college_programs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['semester_id'], ['college_semesters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_college_students_id'), 'college_students', ['id'], unique=False)
    op.create_index(op.f('ix_college_students_roll_number'), 'college_students', ['roll_number'], unique=True)
    op.create_index(op.f('ix_college_students_user_id'), 'college_students', ['user_id'], unique=True)
    op.create_table('lab_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_equipment_id'), 'lab_equipment', ['id'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostel_id', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('occupied', sa.Integer(), nullable=True),
    sa.Column('room_type', sa.String(length=50), nullable=True),
    sa.Column('amenities', sa.String(length=500), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_table('college_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=True),
    sa.Column('enrollment_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('grade_points', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['college_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['semester_id'], ['college_semesters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['college_students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_college_enrollments_id'), 'college_enrollments', ['id'], unique=False)
    op.create_table('hostel_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('allocation_date', sa.DateTime(), nullable=True),
    sa.Column('vacate_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['college_students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hostel_allocations_id'), 'hostel_allocations', ['id'], unique=False)
    op.create_table('hostel_complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('hostel_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['college_faculty.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['college_students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hostel_complaints_id'), 'hostel_complaints', ['id'], unique=False)
    op.create_table('lab_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.String(length=10), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('semester_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['college_courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['semester_id'], ['college_semesters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_schedules_id'), 'lab_schedules', ['id'], unique=False)
    op.create_table('placement_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['placement_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['college_students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_placement_applications_id'), 'placement_applications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_placement_applications_id'), table_name='placement_applications')
    op.drop_table('placement_applications')
    op.drop_index(op.f('ix_lab_schedules_id'), table_name='lab_schedules')
    op.drop_table('lab_schedules')
    op.drop_index(op.f('ix_hostel_complaints_id'), table_name='hostel_complaints')
    op.drop_table('hostel_complaints')
    op.drop_index(op.f('ix_hostel_allocations_id'), table_name='hostel_allocations')
    op.drop_table('hostel_allocations')
    op.drop_index(op.f('ix_college_enrollments_id'), table_name='college_enrollments')
    op.drop_table('college_enrollments')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_lab_equipment_id'), table_name='lab_equipment')
    op.drop_table('lab_equipment')
    op.drop_index(op.f('ix_college_students_user_id'), table_name='college_students')
    op.drop_index(op.f('ix_college_students_roll_number'), table_name='college_students')
    op.drop_index(op.f('ix_college_students_id'), table_name='college_students')
    op.drop_table('college_students')
    op.drop_index(op.f('ix_college_courses_id'), table_name='college_courses')
    op.drop_table('college_courses')
    op.drop_index(op.f('ix_research_publications_id'), table_name='research_publications')
    op.drop_table('research_publications')
    op.drop_index(op.f('ix_research_projects_id'), table_name='research_projects')
    op.drop_table('research_projects')
    op.drop_index(op.f('ix_research_patents_id'), table_name='research_patents')
    op.drop_table('research_patents')
    op.drop_index(op.f('ix_labs_id'), table_name='labs')
    op.drop_table('labs')
    op.drop_index(op.f('ix_hostels_id'), table_name='hostels')
    op.drop_table('hostels')
    op.drop_index(op.f('ix_college_semesters_id'), table_name='college_semesters')
    op.drop_table('college_semesters')
    op.drop_index(op.f('ix_placement_jobs_id'), table_name='placement_jobs')
    op.drop_table('placement_jobs')
    op.drop_index(op.f('ix_college_programs_id'), table_name='college_programs')
    op.drop_table('college_programs')
    op.drop_index(op.f('ix_college_faculty_user_id'), table_name='college_faculty')
    op.drop_index(op.f('ix_college_faculty_id'), table_name='college_faculty')
    op.drop_index(op.f('ix_college_faculty_employee_id'), table_name='college_faculty')
    op.drop_table('college_faculty')
    op.drop_index(op.f('ix_placement_companies_id'), table_name='placement_companies')
    op.drop_table('placement_companies')
    op.drop_index(op.f('ix_college_departments_name'), table_name='college_departments')
    op.drop_index(op.f('ix_college_departments_id'), table_name='college_departments')
    op.drop_table('college_departments')
    # ### end Alembic commands ###
