-- ============================================================================
-- PLAN 6: ALUMNI & PLACEMENT (14 tables)
-- ============================================================================
-- Alumni network, placement tracking, industry partnerships, career services
-- Dependencies: college_students, college_courses, college_departments
-- ============================================================================

-- -----------------------------------------------------------------------------
-- 6.1 COLLEGE_ALUMNI_RECORDS
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS college_alumni_records (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    alumni_number VARCHAR(50) UNIQUE NOT NULL,
    student_id BIGINT UNSIGNED UNIQUE, -- original student record
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone_primary VARCHAR(20),
    phone_secondary VARCHAR(20),
    date_of_birth DATE,
    gender ENUM('male', 'female', 'other', 'prefer_not_to_say'),
    blood_group ENUM('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'),
    graduation_year INT NOT NULL,
    graduation_month ENUM('jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec') DEFAULT 'may',
    degree_type ENUM('bachelor', 'master', 'diploma', 'certificate', 'phd') NOT NULL,
    department_id BIGINT UNSIGNED NOT NULL,
    course_id BIGINT UNSIGNED NOT NULL,
    specialization VARCHAR(255),
    roll_number VARCHAR(100),
    cgpa DECIMAL(4,2),
    division VARCHAR(10),
    current_job_title VARCHAR(255),
    current_company VARCHAR(255),
    industry_sector VARCHAR(255),
    job_type ENUM('full_time', 'part_time', 'freelance', 'self_employed', 'unemployed', 'studying') DEFAULT 'full_time',
    experience_years DECIMAL(4,1) DEFAULT 0.0,
    current_salary DECIMAL(14,2),
    salary_currency VARCHAR(3) DEFAULT 'INR',
    current_city VARCHAR(100),
    current_state VARCHAR(100),
    current_country VARCHAR(100) DEFAULT 'India',
    linkedin_url TEXT,
    facebook_url TEXT,
    twitter_handle VARCHAR(100),
    website_portfolio TEXT,
    skills JSON, -- ["python", "java", "project_management"]
    certifications JSON,
    languages_known JSON,
    is_visible_in_directory BOOLEAN DEFAULT TRUE,
    is_willing_to_mentor BOOLEAN DEFAULT FALSE,
    is_willing_to_hire BOOLEAN DEFAULT FALSE,
    wants_job_alerts BOOLEAN DEFAULT TRUE,
    newsletter_subscription BOOLEAN DEFAULT TRUE,
    last_contacted_date DATE,
    last_contact_method ENUM('email', 'phone', 'meeting', 'event', 'other'),
    engagement_score INT DEFAULT 0, -- calculated from activity
    notes TEXT,
    data_source ENUM('student_record', 'self_registered', 'linkedin_import', 'manual') DEFAULT 'student_record',
    profile_complete_percentage INT DEFAULT 0,
    last_updated_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_alumni_number (alumni_number),
    INDEX idx_student (student_id),
    INDEX idx_graduation (graduation_year, department_id),
    INDEX idx_dept_course (department_id, course_id),
    INDEX idx_email (email),
    INDEX idx_location (current_city, current_state, current_country),
    INDEX idx_company (current_company),
    INDEX idx_skills (skills), -- JSON search depends on MySQL version
    INDEX idx_engagement (engagement_score),
    INDEX idx_mentor (is_willing_to_mentor),
    INDEX idx_visible (is_visible_in_directory),
    FULLTEXT idx_search (first_name, last_name, current_company, current_job_title, skills),
    FOREIGN KEY (student_id) REFERENCES college_students(id) ON DELETE SET NULL,
    FOREIGN KEY (department_id) REFERENCES college_departments(id) ON DELETE RESTRICT,
    FOREIGN KEY (course_id) REFERENCES college_courses(id) ON DELETE RESTRICT,
    CHECK (engagement_score >= 0 AND engagement_score <= 100),
    CHECK (experience_years >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Master alumni records with career tracking';

-- -----------------------------------------------------------------------------
-- 6.2 COLLEGE_ALUMNI_EVENTS
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS college_alumni_events (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    event_code VARCHAR(50) UNIQUE NOT NULL,
    title VARCHAR(500) NOT NULL,
    description LONGTEXT,
    event_type ENUM('reunion', 'networking', 'workshop', 'panel_discussion', 'job_fair', 'fundraising', 'other') DEFAULT 'reunion',
    venue VARCHAR(500),
    city VARCHAR(100),
    state VARCHAR(100),
    country VARCHAR(100) DEFAULT 'India',
    event_date DATE NOT NULL,
    start_time TIME,
    end_time TIME,
    is_virtual BOOLEAN DEFAULT FALSE,
    virtual_meeting_url TEXT,
    registration_required BOOLEAN DEFAULT TRUE,
    registration_deadline DATE,
    max_participants INT UNSIGNED,
    current_registrations INT UNSIGNED DEFAULT 0,
    fee_amount DECIMAL(10,2) DEFAULT 0.00,
    organizer_team JSON, -- ["alumni_office", "placement_cell"]
    host_department_id BIGINT UNSIGNED,
    contact_person VARCHAR(255),
    contact_email VARCHAR(255),
    contact_phone VARCHAR(20),
    sponsor_details JSON,
    agenda JSON, -- scheduled sessions
    attachments JSON, -- poster, brochure URLs
    is_published BOOLEAN DEFAULT FALSE,
    published_at TIMESTAMP NULL,
    created_by BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_event_code (event_code),
    INDEX idx_dates (event_date, registration_deadline),
    INDEX idx_type (event_type),
    INDEX idx_published (is_published),
    INDEX_idx_department (host_department_id),
    FULLTEXT idx_title_desc (title, description),
    FOREIGN KEY (host_department_id) REFERENCES college_departments(id) ON DELETE SET NULL,
    FOREIGN KEY (created_by) REFERENCES college_teachers(id) ON DELETE RESTRICT,
    CHECK (end_time >= start_time OR end_time IS NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Alumni events and reunions';

-- -----------------------------------------------------------------------------
-- 6.3 COLLEGE_ALUMNI_EVENT_ATTENDEES (Junction Table)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS college_alumni_event_attendees (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    event_id BIGINT UNSIGNED NOT NULL,
    attendee_type ENUM('alumni', 'student', 'faculty', 'guest', 'speaker', 'sponsor') DEFAULT 'alumni',
    attendee_id BIGINT UNSIGNED, -- alumni ID or student/faculty ID
    registration_number VARCHAR(50) UNIQUE,
    registration_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    attendance_status ENUM('registered', 'confirmed', 'attended', 'cancelled', 'no_show') DEFAULT 'registered',
    checkin_time TIME,
    checkout_time TIME,
    certificate_issued BOOLEAN DEFAULT FALSE,
    certificate_url TEXT,
    feedback_submitted BOOLEAN DEFAULT FALSE,
    feedback_id BIGINT UNSIGNED,
    special_requirements TEXT,
    dietary_restrictions JSON,
    notes TEXT,
    INDEX idx_event (event_id),
    INDEX idx_attendee (attendee_type, attendee_id),
    INDEX idx_status (attendance_status),
    INDEX idx_certificate (certificate_issued),
    FOREIGN KEY (event_id) REFERENCES college_alumni_events(id) ON DELETE CASCADE,
    FOREIGN KEY (feedback_id) REFERENCES college_alumni_feedback(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Event registration and attendance tracking';

-- -----------------------------------------------------------------------------
-- 6.4 COLLEGE_ALUMNI_DONATIONS
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS college_alumni_donations (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    donation_number VARCHAR(50) UNIQUE NOT NULL,
    donor_id BIGINT UNSIGNED NOT NULL, -- alumni ID
    donation_type ENUM('one_time', 'recurring', 'scholarship', 'infrastructure', 'research', 'other') DEFAULT 'one_time',
    amount DECIMAL(14,2) NOT NULL,
    currency VARCHAR(3) DEFAULT 'INR',
    donation_date DATE NOT NULL,
    payment_method ENUM('cash', 'cheque', 'card', 'online_transfer', 'upi', 'foreign_transfer') DEFAULT 'online_transfer',
    transaction_reference VARCHAR(255) UNIQUE,
    bank_name VARCHAR(255),
    cheque_number VARCHAR(100),
    cheque_date DATE,
    receipt_issued BOOLEAN DEFAULT FALSE,
    receipt_number VARCHAR(100),
    receipt_date DATE,
    tax_benefit_eligible BOOLEAN DEFAULT FALSE,
    tax_exemption_certificate_sent BOOLEAN DEFAULT FALSE,
    dedication TEXT, -- "In memory of...", "For department..."
    restricted_to_department BIGINT UNSIGNED,
    restricted_to_course BIGINT UNSIGNED,
    is_anonymous BOOLEAN DEFAULT FALSE,
    gift_matching_company VARCHAR(255),
    installment_count INT DEFAULT 1,
    installment_frequency ENUM('monthly', 'quarterly', 'annually'),
    next_installment_date DATE,
    campaign_id BIGINT UNSIGNED,
    notes TEXT,
    receipt_generated_at TIMESTAMP NULL,
    receipt_generated_by BIGINT UNSIGNED,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_donation_number (donation_number),
    INDEX idx_donor (donor_id),
    INDEX idx_date (donation_date),
    INDEX idx_type (donation_type),
    INDEX idx_receipt (receipt_number),
    INDEX idx_anonymous (is_anonymous),
    INDEX idx_campaign (campaign_id),
    FOREIGN KEY (donor_id) REFERENCES college_alumni_records(id) ON DELETE RESTRICT,
    FOREIGN KEY (restricted_to_department) REFERENCES college_departments(id) ON DELETE SET NULL,
    FOREIGN KEY (restricted_to_course) REFERENCES college_courses(id) ON DELETE SET NULL,
    FOREIGN KEY (receipt_generated_by) REFERENCES college_teachers(id) ON DELETE SET NULL,
    CHECK (amount > 0),
    CHECK (installment_count >= 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Alumni donation and gift tracking';

-- -----------------------------------------------------------------------------
-- 6.5 COLLEGE_ALUMNI_MENTORSHIP
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS college_alumni_mentorship (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    mentor_alumni_id BIGINT UNSIGNED NOT NULL,
    mentee_type ENUM('student', 'junior_alumni') DEFAULT 'student',
    mentee_id BIGINT UNSIGNED, -- student or junior alumni ID
    mentorship_program_id BIGINT UNSIGNED,
    start_date DATE NOT NULL,
    end_date DATE,
    expected_end_date DATE,
    frequency ENUM('weekly', 'biweekly', 'monthly', 'ad_hoc') DEFAULT 'monthly',
    preferred_contact_mode ENUM('email', 'phone', 'video_call', 'in_person') DEFAULT 'email',
    mentor_availability JSON, -- schedule
    mentorship_goals JSON, -- ["career_guidance", "skill_development"]
    progress_notes TEXT,
    last_contact_date DATE,
    next_meeting_scheduled DATE,
    mentor_satisfaction_rating INT, -- 1-5
    mentee_satisfaction_rating INT,
    status ENUM('active', 'completed', 'paused', 'terminated', 'matched') DEFAULT 'matched',
    termination_reason TEXT,
    terminated_by BIGINT UNSIGNED,
    mentor_agreed_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    mentor_agreed_ip VARCHAR(45),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_mentor (mentor_alumni_id),
    INDEX idx_mentee (mentee_type, mentee_id),
    INDEX idx_status (status),
    INDEX idx_program (mentorship_program_id),
    INDEX idx_dates (start_date, end_date),
    FOREIGN KEY (mentor_alumni_id) REFERENCES college_alumni_records(id) ON DELETE CASCADE,
    FOREIGN KEY (mentee_id) REFERENCES college_students(id) ON DELETE CASCADE,
    FOREIGN KEY (terminated_by) REFERENCES college_teachers(id) ON DELETE SET NULL,
    CHECK (end_date IS NULL OR end_date >= start_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Alumni-student mentorship pairings and progress';

-- -----------------------------------------------------------------------------
-- 6.6 COLLEGE_ALUMNI_EMPLOYMENT
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS college_alumni_employment (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    alumni_id BIGINT UNSIGNED NOT NULL,
    employer_name VARCHAR(255) NOT NULL,
    job_title VARCHAR(255) NOT NULL,
    employment_type ENUM('full_time', 'part_time', 'contract', 'internship', 'freelance', 'self_employed') DEFAULT 'full_time',
    industry_sector VARCHAR(255),
    job_function VARCHAR(255),
    location_city VARCHAR(100),
    location_state VARCHAR(100),
    location_country VARCHAR(100) DEFAULT 'India',
    start_date DATE NOT NULL,
    end_date DATE,
    is_current BOOLEAN DEFAULT TRUE,
    salary_band VARCHAR(50), -- "10-15 LPA", "undisclosed"
    responsibilities TEXT,
    achievements TEXT,
    skills_used JSON,
    company_size ENUM('startup', 'small', 'medium', 'large', 'enterprise'),
    company_type ENUM('product', 'service', 'consulting', 'government', 'ngo'),
    reporting_manager VARCHAR(255),
    company_website TEXT,
    verified BOOLEAN DEFAULT FALSE,
    verified_by BIGINT UNSIGNED,
    verified_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_alumni (alumni_id),
    INDEX idx_employer (employer_name),
    INDEX idx_current (is_current),
    INDEX idx_dates (start_date, end_date),
    INDEX idx_industry (industry_sector),
    FOREIGN KEY (alumni_id) REFERENCES college_alumni_records(id) ON DELETE CASCADE,
    FOREIGN KEY (verified_by) REFERENCES college_teachers(id) ON DELETE SET NULL,
    CHECK (end_date IS NULL OR end_date >= start_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Alumni employment history and career progression';

-- -----------------------------------------------------------------------------
-- 6.7 COLLEGE_INDUSTRY_PARTNERS
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS college_industry_partners (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    partner_code VARCHAR(50) UNIQUE NOT NULL,
    company_name VARCHAR(255) NOT NULL,
    legal_name VARCHAR(500),
    industry_sector VARCHAR(255),
    company_size ENUM('startup', 'small', 'medium', 'large', 'enterprise', 'mnc'),
    company_type ENUM('product', 'service', 'consulting', 'manufacturing', 'government', 'ngo'),
    contact_person_name VARCHAR(255),
    contact_designation VARCHAR(100),
    contact_email VARCHAR(255) UNIQUE,
    contact_phone_primary VARCHAR(20),
    contact_phone_secondary VARCHAR(20),
    website_url TEXT,
    linkedin_company_url TEXT,
    hrd_email VARCHAR(255),
    hrd_phone VARCHAR(20),
    address_line1 TEXT,
    address_line2 TEXT,
    city VARCHAR(100),
    state VARCHAR(100),
    pincode VARCHAR(20),
    country VARCHAR(100) DEFAULT 'India',
    gst_number VARCHAR(50),
    pan_number VARCHAR(50),
    partnership_level ENUM('platinum', 'gold', 'silver', 'bronze', 'associate') DEFAULT 'associate',
    partnership_start_date DATE,
    partnership_end_date DATE,
    total_mou_signed INT UNSIGNED DEFAULT 0,
    active_mou_count INT UNSIGNED DEFAULT 0,
    last_campus_visit_date DATE,
    offers_extended_count INT UNSIGNED DEFAULT 0,
    offers_accepted_count INT UNSIGNED DEFAULT 0,
    placement_conversion_rate DECIMAL(5,2) DEFAULT 0.00,
    is_active BOOLEAN DEFAULT TRUE,
    is_featured_partner BOOLEAN DEFAULT FALSE,
    logo_url TEXT,
    description TEXT,
    tags JSON, -- ["tech", "startup", "fortune500"]
    company_culture_rating INT,
    created_by BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_partner_code (partner_code),
    INDEX idx_company (company_name),
    INDEX idx_sector (industry_sector),
    INDEX idx_level (partnership_level),
    INDEX idx_contact (contact_email, contact_phone_primary),
    INDEX idx_active (is_active),
    INDEX idx_featured (is_featured_partner),
    FULLTEXT idx_search (company_name, description, industry_sector, tags),
    FOREIGN KEY (created_by) REFERENCES college_teachers(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Industry partner relationships and MOU tracking';

-- -----------------------------------------------------------------------------
-- 6.8 COLLEGE_INTERNSHIPS
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS college_internships (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    internship_code VARCHAR(50) UNIQUE NOT NULL,
    title VARCHAR(500) NOT NULL,
    description LONGTEXT,
    company_id BIGINT UNSIGNED NOT NULL,
    industry_sector VARCHAR(255),
    job_function VARCHAR(255),
    location_type ENUM('on_site', 'remote', 'hybrid') DEFAULT 'on_site',
    location_city VARCHAR(100),
    location_state VARCHAR(100),
    work_from_home_possible BOOLEAN DEFAULT FALSE,
    internship_type ENUM('summer', 'winter', 'semester', 'year_long', 'project_based') DEFAULT 'summer',
    duration_months DECIMAL(4,1) NOT NULL, -- e.g., 2.0 = 2 months
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    stipend_amount DECIMAL(10,2),
    stipend_frequency ENUM('monthly', 'weekly', 'lump_sum', 'unpaid') DEFAULT 'monthly',
    stipend_currency VARCHAR(3) DEFAULT 'INR',
    eligibility_branch JSON, -- ["cse", "ece", "mechanical"]
    eligibility_min_cgpa DECIMAL(4,2),
    eligibility_semester_min INT,
    eligibility_semester_max INT,
    required_skills JSON,
    preferred_skills JSON,
    selection_process JSON, -- ["resume_screening", "aptitude_test", "interview"]
    application_deadline DATE,
    posting_date DATE,
    total_openings INT UNSIGNED DEFAULT 1,
    filled_count INT UNSIGNED DEFAULT 0,
    status ENUM('draft', 'published', 'closed', 'filled', 'cancelled') DEFAULT 'draft',
    is_featured BOOLEAN DEFAULT FALSE,
    featured_until DATE,
    attachment_urls JSON, -- job description PDF
    posted_by BIGINT UNSIGNED NOT NULL,
    posted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    approved_by BIGINT UNSIGNED,
    approved_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_internship_code (internship_code),
    INDEX idx_company (company_id),
    INDEX idx_dates (start_date, end_date),
    INDEX idx_deadline (application_deadline),
    INDEX idx_status (status),
    INDEX idx_featured (is_featured, featured_until),
    INDEX idx_type_location (internship_type, location_type, location_city),
    FULLTEXT idx_title_desc (title, description, required_skills),
    FOREIGN KEY (company_id) REFERENCES college_industry_partners(id) ON DELETE CASCADE,
    FOREIGN KEY (posted_by) REFERENCES college_teachers(id) ON DELETE RESTRICT,
    FOREIGN KEY (approved_by) REFERENCES college_teachers(id) ON DELETE SET NULL,
    CHECK (end_date > start_date),
    CHECK (duration_months > 0),
    CHECK (total_openings >= filled_count)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Internship opportunity postings';

-- -----------------------------------------------------------------------------
-- 6.9 COLLEGE_INTERNSHIP_APPLICATIONS
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS college_internship_applications (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    internship_id BIGINT UNSIGNED NOT NULL,
    student_id BIGINT UNSIGNED NOT NULL,
    application_number VARCHAR(50) UNIQUE NOT NULL,
    application_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status ENUM('applied', 'shortlisted', 'interview_scheduled', 'selected', 'rejected', 'withdrawn', 'offer_declined') DEFAULT 'applied',
    resume_url TEXT NOT NULL,
    cover_letter TEXT,
    current_semester INT,
    expected_graduation_date DATE,
    gpa DECIMAL(4,2),
    relevant_experience TEXT,
    why_interested TEXT,
    availability_start_date DATE,
    availability_end_date DATE,
    interviewer_ratings JSON, -- {"technical": 4, "communication": 5}
    interview_feedback TEXT,
    interview_date DATE,
    interview_time TIME,
    interview_panel_json JSON,
    selected_for_another_internship BOOLEAN DEFAULT FALSE,
    other_offer_company VARCHAR(255),
    offer_received_date DATE,
    offer_accepted BOOLEAN DEFAULT FALSE,
    offer_accepted_date DATE,
    expected_stipend DECIMAL(10,2),
    negotiation_notes TEXT,
    notes_internal TEXT,
    applied_through ENUM('portal', 'referral', 'company_website', 'event', 'other') DEFAULT 'portal',
    referral_alumni_id BIGINT UNSIGNED,
    referral_bonus_eligible BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_application_number (application_number),
    INDEX idx_internship_student (internship_id, student_id),
    INDEX idx_student_status (student_id, status),
    INDEX idx_status (status),
    INDEX idx_interview (interview_date),
    INDEX idx_offer (offer_received_date, offer_accepted),
    INDEX idx_referral (referral_alumni_id),
    FULLTEXT idx_student_notes (cover_letter, relevant_experience, why_interested),
    FOREIGN KEY (internship_id) REFERENCES college_internships(id) ON DELETE CASCADE,
    FOREIGN KEY (student_id) REFERENCES college_students(id) ON DELETE CASCADE,
    FOREIGN KEY (referral_alumni_id) REFERENCES college_alumni_records(id) ON DELETE SET NULL,
    UNIQUE KEY uk_internship_student (internship_id, student_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Student internship applications and tracking';

-- -----------------------------------------------------------------------------
-- 6.10 COLLEGE_INTERNSHIP_EVALUATIONS
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS college_internship_evaluations (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    application_id BIGINT UNSIGNED UNIQUE NOT NULL, -- one evaluation per application
    evaluated_by BIGINT UNSIGNED NOT NULL, -- faculty supervisor
    technical_skills_rating INT CHECK (technical_skills_rating BETWEEN 1 AND 10),
    professional_conduct_rating INT CHECK (professional_conduct_rating BETWEEN 1 AND 10),
    punctuality_rating INT CHECK (punctuality_rating BETWEEN 1 AND 10),
    communication_rating INT CHECK (communication_rating BETWEEN 1 AND 10),
    task_completion_rating INT CHECK (task_completion_rating BETWEEN 1 AND 10),
    overall_rating DECIMAL(4,2) AS ((technical_skills_rating + professional_conduct_rating + punctuality_rating + communication_rating + task_completion_rating) / 5) STORED,
    supervisor_feedback TEXT,
    student_self_evaluation TEXT,
    project_deliverables JSON, -- files or links
    skills_acquired JSON,
    hours_worked INT UNSIGNED,
    days_present INT UNSIGNED,
    recommendation_letter_sent BOOLEAN DEFAULT FALSE,
    recommendation_letter_url TEXT,
    is_eligible_for_credit BOOLEAN DEFAULT FALSE,
    credit_hours_awarded INT,
    evaluation_completed BOOLEAN DEFAULT FALSE,
    evaluation_completed_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_application (application_id),
    INDEX idx_evaluator (evaluated_by),
    INDEX idx_rating (overall_rating),
    FOREIGN KEY (application_id) REFERENCES college_internship_applications(id) ON DELETE CASCADE,
    FOREIGN KEY (evaluated_by) REFERENCES college_teachers(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Faculty evaluation of student internship performance';

-- -----------------------------------------------------------------------------
-- 6.11 COLLEGE_PLACEMENT_DRIVES
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS college_placement_drives (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    drive_code VARCHAR(50) UNIQUE NOT NULL,
    company_id BIGINT UNSIGNED NOT NULL,
    drive_title VARCHAR(500) NOT NULL,
    job_profile VARCHAR(255) NOT NULL,
    description LONGTEXT,
    job_location_type ENUM('on_site', 'remote', 'hybrid') DEFAULT 'on_site',
    job_location_cities JSON,
    job_department VARCHAR(255),
    job_band VARCHAR(100), -- salary band
    package_components JSON, -- ["base", "bonus", "stock", "benefits"]
    ctc_min DECIMAL(14,2), -- total compensation
    ctc_max DECIMAL(14,2),
    ctc_currency VARCHAR(3) DEFAULT 'INR',
    eligibility_cgpa_min DECIMAL(4,2),
    eligibility_backlogs_allowed INT DEFAULT 0,
    eligibility_branches JSON, -- ["cse", "it", "ece"]
    eligibility_semester_min INT,
    eligibility_semester_max INT,
    selection_process JSON, -- ["resume_screening", "online_test", "technical_interview", "hr"]
    rounds_details JSON, -- detailed descriptions of each round
    application_deadline DATE,
    drive_date DATE NOT NULL,
    drive_start_time TIME,
    drive_end_time TIME,
    venue VARCHAR(500),
    is_virtual BOOLEAN DEFAULT FALSE,
    virtual_meeting_url TEXT,
    registration_required BOOLEAN DEFAULT TRUE,
    max_registrations INT UNSIGNED,
    current_registrations INT UNSIGNED DEFAULT 0,
    offers_extended INT UNSIGNED DEFAULT 0,
    offers_accepted INT UNSIGNED DEFAULT 0,
    status ENUM('draft', 'published', 'registration_open', 'in_progress', 'completed', 'cancelled') DEFAULT 'draft',
    drive_coordinator_id BIGINT UNSIGNED,
    placement_officer_id BIGINT UNSIGNED,
    company_hr_contacts JSON,
    company_representatives JSON,
    is_featured BOOLEAN DEFAULT FALSE,
    attachment_urls JSON, -- job description, posters
    remarks TEXT,
    created_by BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_drive_code (drive_code),
    INDEX idx_company (company_id),
    INDEX idx_dates (drive_date, application_deadline),
    INDEX idx_status (status),
    INDEX idx_registrations (current_registrations, max_registrations),
    INDEX idx_featured (is_featured),
    FOREIGN KEY (company_id) REFERENCES college_industry_partners(id) ON DELETE CASCADE,
    FOREIGN KEY (drive_coordinator_id) REFERENCES college_teachers(id) ON DELETE SET NULL,
    FOREIGN KEY (placement_officer_id) REFERENCES college_teachers(id) ON DELETE SET NULL,
    FOREIGN KEY (created_by) REFERENCES college_teachers(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Campus recruitment drive organization';

-- -----------------------------------------------------------------------------
-- 6.12 COLLEGE_PLACEMENT_APPLICATIONS
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS college_placement_applications (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    drive_id BIGINT UNSIGNED NOT NULL,
    student_id BIGINT UNSIGNED NOT NULL,
    application_number VARCHAR(50) UNIQUE NOT NULL,
    application_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status ENUM('applied', 'shortlisted_test', 'shortlisted_interview', 'selected', 'rejected', 'offer_extended', 'offer_accepted', 'offer_declined', 'withdrawn') DEFAULT 'applied',
    resume_url TEXT NOT NULL,
    applied_for_profile VARCHAR(255),
    expected_ctc DECIMAL(14,2),
    resume_shortlisted BOOLEAN DEFAULT FALSE,
    shortlisted_at TIMESTAMP NULL,
    shortlisted_by BIGINT UNSIGNED,
    test_round_cleared BOOLEAN DEFAULT FALSE,
    test_score DECIMAL(6,2),
    test_rank INT UNSIGNED,
    interview_round_cleared BOOLEAN DEFAULT FALSE,
    interview_feedback TEXT,
    interviewer_ratings JSON,
    final_verdict ENUM('selected', 'rejected', 'waitlisted'),
    offer_letter_url TEXT,
    offer_letter_date DATE,
    offer_validity_date DATE,
    offered_ctc DECIMAL(14,2),
    offered_currency VARCHAR(3) DEFAULT 'INR',
    offer_accepted BOOLEAN DEFAULT FALSE,
    offer_accepted_date DATE,
    joining_date DATE,
    actual_ctc DECIMAL(14,2),
    actual_currency VARCHAR(3),
    feedback_from_company TEXT,
    student_feedback TEXT,
    placement_remarks_internal TEXT,
    applied_through ENUM('direct', 'referral', 'campus', 'alumni_referral') DEFAULT 'campus',
    referral_by_alumni_id BIGINT UNSIGNED,
    pre_placement_training_completed BOOLEAN DEFAULT FALSE,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_application_number (application_number),
    INDEX idx_drive_student (drive_id, student_id),
    INDEX idx_student_status (student_id, status),
    INDEX idx_status (status),
    INDEX idx_drive_status (drive_id, status),
    INDEX idx_offer (offer_letter_date, offer_accepted),
    INDEX idx_joining (joining_date),
    INDEX idx_referral (referral_by_alumni_id),
    FOREIGN KEY (drive_id) REFERENCES college_placement_drives(id) ON DELETE CASCADE,
    FOREIGN KEY (student_id) REFERENCES college_students(id) ON DELETE CASCADE,
    FOREIGN KEY (referral_by_alumni_id) REFERENCES college_alumni_records(id) ON DELETE SET NULL,
    FOREIGN KEY (shortlisted_by) REFERENCES college_teachers(id) ON DELETE SET NULL,
    UNIQUE KEY uk_drive_student (drive_id, student_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Student applications to campus placement drives';

-- -----------------------------------------------------------------------------
-- 6.13 COLLEGE_PLACEMENT_OFFERS
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS college_placement_offers (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    offer_number VARCHAR(50) UNIQUE NOT NULL,
    application_id BIGINT UNSIGNED NOT NULL,
    student_id BIGINT UNSIGNED NOT NULL,
    company_id BIGINT UNSIGNED NOT NULL,
    job_profile VARCHAR(255) NOT NULL,
    department VARCHAR(255),
    location_city VARCHAR(100),
    location_state VARCHAR(100),
    ctc_offered DECIMAL(14,2) NOT NULL,
    ctc_currency VARCHAR(3) DEFAULT 'INR',
    gross_salary DECIMAL(14,2),
    fixed_component DECIMAL(14,2),
    variable_component DECIMAL(14,2),
    joining_bonus DECIMAL(14,2),
    stock_options BOOLEAN DEFAULT FALSE,
    other_benefits JSON,
    joining_date DATE NOT NULL,
    probation_period_months INT DEFAULT 6,
    reporting_manager VARCHAR(255),
    hr_contact_email VARCHAR(255),
    hr_contact_phone VARCHAR(20),
    offer_letter_url TEXT,
    offer_letter_sent_date DATE,
    student_response_date DATE,
    student_response ENUM('accepted', 'declined', 'negotiating', 'no_response') DEFAULT 'no_response',
    decline_reason TEXT,
    negotiation_notes TEXT,
    final_ctc DECIMAL(14,2),
    status ENUM('offered', 'accepted', 'declined', 'withdrawn', 'joined', 'no_show') DEFAULT 'offered',
    placement_officer_id BIGINT UNSIGNED,
    approval_status ENUM('pending', 'approved', 'rejected') DEFAULT 'approved',
    approved_by BIGINT UNSIGNED,
    approved_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_offer_number (offer_number),
    INDEX idx_application (application_id),
    INDEX idx_student (student_id),
    INDEX idx_company (company_id),
    INDEX idx_status (status),
    INDEX idx_joining (joining_date),
    INDEX idx_response (student_response),
    FOREIGN KEY (application_id) REFERENCES college_placement_applications(id) ON DELETE CASCADE,
    FOREIGN KEY (student_id) REFERENCES college_students(id) ON DELETE CASCADE,
    FOREIGN KEY (company_id) REFERENCES college_industry_partners(id) ON DELETE RESTRICT,
    FOREIGN KEY (placement_officer_id) REFERENCES college_teachers(id) ON DELETE SET NULL,
    FOREIGN KEY (approved_by) REFERENCES college_teachers(id) ON DELETE SET NULL,
    UNIQUE KEY uk_student_offer (student_id, company_id, joining_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Final job offers and acceptance tracking';

-- -----------------------------------------------------------------------------
-- 6.14 COLLEGE_INDUSTRY_VISITS
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS college_industry_visits (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    visit_code VARCHAR(50) UNIQUE NOT NULL,
    company_id BIGINT UNSIGNED NOT NULL,
    visit_title VARCHAR(500) NOT NULL,
    purpose ENUM('faculty_training', 'student_visit', 'research_collaboration', 'moU_signing', 'other') DEFAULT 'student_visit',
    visit_date DATE NOT NULL,
    start_time TIME,
    end_time TIME,
    location_address TEXT,
    contact_person_name VARCHAR(255),
    contact_phone VARCHAR(20),
    contact_email VARCHAR(255),
    max_participants INT UNSIGNED,
    participant_type ENUM('students', 'faculty', 'both') DEFAULT 'students',
    participant_departments JSON, -- ["cse", "ece", "mechanical"]
    faculty_coordinator_id BIGINT UNSIGNED NOT NULL,
    transportation_required BOOLEAN DEFAULT FALSE,
    transportation_details TEXT,
    estimated_cost DECIMAL(10,2),
    actual_cost DECIMAL(10,2),
    funding_source ENUM('department', 'college', 'sponsor', 'self') DEFAULT 'department',
    objectives TEXT,
    outcomes TEXT,
    report_url TEXT,
    photos_urls JSON,
    is_approved BOOLEAN DEFAULT FALSE,
    approved_by BIGINT UNSIGNED,
    approved_at TIMESTAMP NULL,
    status ENUM('planned', 'approved', 'scheduled', 'completed', 'cancelled') DEFAULT 'planned',
    cancellation_reason TEXT,
    feedback_summary TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_visit_code (visit_code),
    INDEX idx_company (company_id),
    INDEX idx_dates (visit_date),
    INDEX idx_status (status),
    INDEX idx_approval (is_approved),
    INDEX idx_coordinator (faculty_coordinator_id),
    FOREIGN KEY (company_id) REFERENCES college_industry_partners(id) ON DELETE CASCADE,
    FOREIGN KEY (faculty_coordinator_id) REFERENCES college_teachers(id) ON DELETE RESTRICT,
    FOREIGN KEY (approved_by) REFERENCES college_teachers(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Faculty/student industry visits and collaborations';

-- ============================================================================
-- PLAN 6 COMPLETE: 14 tables created successfully
-- ============================================================================
