# School Notes Constants
# ======================

# Note Types
NOTE_TYPE_PDF = "pdf"
NOTE_TYPE_PPT = "ppt"
NOTE_TYPE_PPTX = "pptx"
NOTE_TYPE_DOC = "doc"
NOTE_TYPE_DOCX = "docx"
NOTE_TYPE_VIDEO = "video"
NOTE_TYPE_IMAGE = "image"

NOTE_TYPES = [
    NOTE_TYPE_PDF,
    NOTE_TYPE_PPT,
    NOTE_TYPE_PPTX,
    NOTE_TYPE_DOC,
    NOTE_TYPE_DOCX,
    NOTE_TYPE_VIDEO,
    NOTE_TYPE_IMAGE
]

# Note Status
NOTE_STATUS_PENDING = "pending"
NOTE_STATUS_APPROVED = "approved"
NOTE_STATUS_REJECTED = "rejected"
NOTE_STATUS_ARCHIVED = "archived"

NOTE_STATUSES = [
    NOTE_STATUS_PENDING,
    NOTE_STATUS_APPROVED,
    NOTE_STATUS_REJECTED,
    NOTE_STATUS_ARCHIVED
]

# File Size Limits (in bytes)
MAX_FILE_SIZE = 50 * 1024 * 1024  # 50MB
MAX_VIDEO_SIZE = 200 * 1024 * 1024  # 200MB

# Allowed Extensions
ALLOWED_DOCUMENT_EXTENSIONS = [".pdf", ".doc", ".docx", ".ppt", ".pptx", ".txt"]
ALLOWED_VIDEO_EXTENSIONS = [".mp4", ".avi", ".mov", ".mkv"]
ALLOWED_IMAGE_EXTENSIONS = [".jpg", ".jpeg", ".png", ".gif", ".webp"]
ALLOWED_ALL_EXTENSIONS = ALLOWED_DOCUMENT_EXTENSIONS + ALLOWED_VIDEO_EXTENSIONS + ALLOWED_IMAGE_EXTENSIONS


__all__ = [
    "NOTE_TYPES",
    "NOTE_TYPE_PDF",
    "NOTE_TYPE_PPT",
    "NOTE_TYPE_PPTX",
    "NOTE_TYPE_DOC",
    "NOTE_TYPE_DOCX",
    "NOTE_TYPE_VIDEO",
    "NOTE_TYPE_IMAGE",
    "NOTE_STATUSES",
    "NOTE_STATUS_PENDING",
    "NOTE_STATUS_APPROVED",
    "NOTE_STATUS_REJECTED",
    "NOTE_STATUS_ARCHIVED",
    "MAX_FILE_SIZE",
    "MAX_VIDEO_SIZE",
    "ALLOWED_DOCUMENT_EXTENSIONS",
    "ALLOWED_VIDEO_EXTENSIONS",
    "ALLOWED_IMAGE_EXTENSIONS",
    "ALLOWED_ALL_EXTENSIONS"
]