# School Groups Constants
# ======================

# Group Type
GROUP_TYPE_PUBLIC = "public"
GROUP_TYPE_PRIVATE = "private"
GROUP_TYPE_RESTRICTED = "restricted"

GROUP_TYPES = [
    GROUP_TYPE_PUBLIC,
    GROUP_TYPE_PRIVATE,
    GROUP_TYPE_RESTRICTED
]

# Group Status
GROUP_STATUS_ACTIVE = "active"
GROUP_STATUS_INACTIVE = "inactive"
GROUP_STATUS_ARCHIVED = "archived"

GROUP_STATUSES = [
    GROUP_STATUS_ACTIVE,
    GROUP_STATUS_INACTIVE,
    GROUP_STATUS_ARCHIVED
]

# Member Role
MEMBER_ROLE_ADMIN = "admin"
MEMBER_ROLE_MODERATOR = "moderator"
MEMBER_ROLE_MEMBER = "member"

MEMBER_ROLES = [
    MEMBER_ROLE_ADMIN,
    MEMBER_ROLE_MODERATOR,
    MEMBER_ROLE_MEMBER
]

# Post Status
POST_STATUS_DRAFT = "draft"
POST_STATUS_PUBLISHED = "published"
POST_STATUS_DELETED = "deleted"
POST_STATUS_HIDDEN = "hidden"

POST_STATUSES = [
    POST_STATUS_DRAFT,
    POST_STATUS_PUBLISHED,
    POST_STATUS_DELETED,
    POST_STATUS_HIDDEN
]

# Group Settings
MAX_GROUP_NAME_LENGTH = 100
MAX_GROUP_DESCRIPTION_LENGTH = 500
MAX_MEMBERS_DEFAULT = 100
MAX_POST_LENGTH = 2000


__all__ = [
    "GROUP_TYPES",
    "GROUP_TYPE_PUBLIC",
    "GROUP_TYPE_PRIVATE",
    "GROUP_TYPE_RESTRICTED",
    "GROUP_STATUSES",
    "GROUP_STATUS_ACTIVE",
    "GROUP_STATUS_INACTIVE",
    "GROUP_STATUS_ARCHIVED",
    "MEMBER_ROLES",
    "MEMBER_ROLE_ADMIN",
    "MEMBER_ROLE_MODERATOR",
    "MEMBER_ROLE_MEMBER",
    "POST_STATUSES",
    "POST_STATUS_DRAFT",
    "POST_STATUS_PUBLISHED",
    "POST_STATUS_DELETED",
    "POST_STATUS_HIDDEN",
    "MAX_GROUP_NAME_LENGTH",
    "MAX_GROUP_DESCRIPTION_LENGTH",
    "MAX_MEMBERS_DEFAULT",
    "MAX_POST_LENGTH"
]