"""add soft delete columns to college models

Revision ID: b5c8ae3a83ac
Revises: 2c2a19a897c8
Create Date: 2026-05-06 19:26:16.609903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5c8ae3a83ac'
down_revision: Union[str, Sequence[str], None] = '2c2a19a897c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add soft delete columns to college_faculty
    op.add_column('college_faculty', sa.Column('is_deleted', sa.Boolean(), nullable=False, default=False))
    op.add_column('college_faculty', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_college_faculty_is_deleted', 'college_faculty', ['is_deleted'], unique=False)

    # Add soft delete columns to college_students
    op.add_column('college_students', sa.Column('is_deleted', sa.Boolean(), nullable=False, default=False))
    op.add_column('college_students', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_college_students_is_deleted', 'college_students', ['is_deleted'], unique=False)

    # Add soft delete columns to college_courses
    op.add_column('college_courses', sa.Column('is_deleted', sa.Boolean(), nullable=False, default=False))
    op.add_column('college_courses', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_college_courses_is_deleted', 'college_courses', ['is_deleted'], unique=False)

    # Add soft delete columns to college_programs
    op.add_column('college_programs', sa.Column('is_deleted', sa.Boolean(), nullable=False, default=False))
    op.add_column('college_programs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_college_programs_is_deleted', 'college_programs', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove soft delete columns from college_programs
    op.drop_index('ix_college_programs_is_deleted', table_name='college_programs')
    op.drop_column('college_programs', 'deleted_at')
    op.drop_column('college_programs', 'is_deleted')

    # Remove soft delete columns from college_courses
    op.drop_index('ix_college_courses_is_deleted', table_name='college_courses')
    op.drop_column('college_courses', 'deleted_at')
    op.drop_column('college_courses', 'is_deleted')

    # Remove soft delete columns from college_students
    op.drop_index('ix_college_students_is_deleted', table_name='college_students')
    op.drop_column('college_students', 'deleted_at')
    op.drop_column('college_students', 'is_deleted')

    # Remove soft delete columns from college_faculty
    op.drop_index('ix_college_faculty_is_deleted', table_name='college_faculty')
    op.drop_column('college_faculty', 'deleted_at')
    op.drop_column('college_faculty', 'is_deleted')
    # ### end Alembic commands ###
