# School Account Section Constants
# =============================

# Fee Types
FEE_TYPE_TUITION = "tuition"
FEE_TYPE_ADMISSION = "admission"
FEE_TYPE_EXAM = "exam"
FEE_TYPE_LIBRARY = "library"
FEE_TYPE_TRANSPORT = "transport"
FEE_TYPE_HOSTEL = "hostel"
FEE_TYPE_MISCELLANEOUS = "miscellaneous"

FEE_TYPES = [
    FEE_TYPE_TUITION,
    FEE_TYPE_ADMISSION,
    FEE_TYPE_EXAM,
    FEE_TYPE_LIBRARY,
    FEE_TYPE_TRANSPORT,
    FEE_TYPE_HOSTEL,
    FEE_TYPE_MISCELLANEOUS
]

# Payment Status
PAYMENT_STATUS_PENDING = "pending"
PAYMENT_STATUS_PAID = "paid"
PAYMENT_STATUS_PARTIAL = "partial"
PAYMENT_STATUS_OVERDUE = "overdue"
PAYMENT_STATUS_EXEMPTED = "exempted"

PAYMENT_STATUSES = [
    PAYMENT_STATUS_PENDING,
    PAYMENT_STATUS_PAID,
    PAYMENT_STATUS_PARTIAL,
    PAYMENT_STATUS_OVERDUE,
    PAYMENT_STATUS_EXEMPTED
]

# Expense Categories
EXPENSE_CATEGORY_SALARY = "salary"
EXPENSE_CATEGORY_MAINTENANCE = "maintenance"
EXPENSE_CATEGORY_UTILITIES = "utilities"
EXPENSE_CATEGORY_SUPPLIES = "supplies"
EXPENSE_CATEGORY_TRANSPORT = "transport"
EXPENSE_CATEGORY_EVENTS = "events"
EXPENSE_CATEGORY_MARKETING = "marketing"
EXPENSE_CATEGORY_MISCELLANEOUS = "miscellaneous"

EXPENSE_CATEGORIES = [
    EXPENSE_CATEGORY_SALARY,
    EXPENSE_CATEGORY_MAINTENANCE,
    EXPENSE_CATEGORY_UTILITIES,
    EXPENSE_CATEGORY_SUPPLIES,
    EXPENSE_CATEGORY_TRANSPORT,
    EXPENSE_CATEGORY_EVENTS,
    EXPENSE_CATEGORY_MARKETING,
    EXPENSE_CATEGORY_MISCELLANEOUS
]

# Payment Methods
PAYMENT_METHOD_CASH = "cash"
PAYMENT_METHOD_BANK_TRANSFER = "bank_transfer"
PAYMENT_METHOD_CARD = "card"
PAYMENT_METHOD_CHEQUE = "cheque"
PAYMENT_METHOD_ONLINE = "online"

PAYMENT_METHODS = [
    PAYMENT_METHOD_CASH,
    PAYMENT_METHOD_BANK_TRANSFER,
    PAYMENT_METHOD_CARD,
    PAYMENT_METHOD_CHEQUE,
    PAYMENT_METHOD_ONLINE
]


__all__ = [
    "FEE_TYPES",
    "FEE_TYPE_TUITION",
    "FEE_TYPE_ADMISSION",
    "FEE_TYPE_EXAM",
    "FEE_TYPE_LIBRARY",
    "FEE_TYPE_TRANSPORT",
    "FEE_TYPE_HOSTEL",
    "FEE_TYPE_MISCELLANEOUS",
    "PAYMENT_STATUSES",
    "PAYMENT_STATUS_PENDING",
    "PAYMENT_STATUS_PAID",
    "PAYMENT_STATUS_PARTIAL",
    "PAYMENT_STATUS_OVERDUE",
    "PAYMENT_STATUS_EXEMPTED",
    "EXPENSE_CATEGORIES",
    "EXPENSE_CATEGORY_SALARY",
    "EXPENSE_CATEGORY_MAINTENANCE",
    "EXPENSE_CATEGORY_UTILITIES",
    "EXPENSE_CATEGORY_SUPPLIES",
    "EXPENSE_CATEGORY_TRANSPORT",
    "EXPENSE_CATEGORY_EVENTS",
    "EXPENSE_CATEGORY_MARKETING",
    "EXPENSE_CATEGORY_MISCELLANEOUS",
    "PAYMENT_METHODS",
    "PAYMENT_METHOD_CASH",
    "PAYMENT_METHOD_BANK_TRANSFER",
    "PAYMENT_METHOD_CARD",
    "PAYMENT_METHOD_CHEQUE",
    "PAYMENT_METHOD_ONLINE"
]