# School Library Constants
# ===================

# Book Categories
CATEGORY_FICTION = "fiction"
CATEGORY_NON_FICTION = "non-fiction"
CATEGORY_TEXTBOOK = "textbook"
CATEGORY_REFERENCE = "reference"
CATEGORY_MAGAZINE = "magazine"
CATEGORY_JOURNAL = "journal"

CATEGORIES = [
    CATEGORY_FICTION,
    CATEGORY_NON_FICTION,
    CATEGORY_TEXTBOOK,
    CATEGORY_REFERENCE,
    CATEGORY_MAGAZINE,
    CATEGORY_JOURNAL
]

# Loan Status
LOAN_STATUS_ISSUED = "issued"
LOAN_STATUS_RETURNED = "returned"
LOAN_STATUS_OVERDUE = "overdue"
LOAN_STATUS_LOST = "lost"

LOAN_STATUSES = [
    LOAN_STATUS_ISSUED,
    LOAN_STATUS_RETURNED,
    LOAN_STATUS_OVERDUE,
    LOAN_STATUS_LOST
]

# Reservation Status
RESERVATION_STATUS_PENDING = "pending"
RESERVATION_STATUS_FULFILLED = "fulfilled"
RESERVATION_STATUS_CANCELLED = "cancelled"

RESERVATION_STATUSES = [
    RESERVATION_STATUS_PENDING,
    RESERVATION_STATUS_FULFILLED,
    RESERVATION_STATUS_CANCELLED
]

# Loan Period (days)
DEFAULT_LOAN_PERIOD = 14
MAX_LOAN_PERIOD = 30
MAX_BOOKS_PER_STUDENT = 3


__all__ = [
    "CATEGORIES",
    "CATEGORY_FICTION",
    "CATEGORY_NON_FICTION",
    "CATEGORY_TEXTBOOK",
    "CATEGORY_REFERENCE",
    "CATEGORY_MAGAZINE",
    "CATEGORY_JOURNAL",
    "LOAN_STATUSES",
    "LOAN_STATUS_ISSUED",
    "LOAN_STATUS_RETURNED",
    "LOAN_STATUS_OVERDUE",
    "LOAN_STATUS_LOST",
    "RESERVATION_STATUSES",
    "RESERVATION_STATUS_PENDING",
    "RESERVATION_STATUS_FULFILLED",
    "RESERVATION_STATUS_CANCELLED",
    "DEFAULT_LOAN_PERIOD",
    "MAX_LOAN_PERIOD",
    "MAX_BOOKS_PER_STUDENT"
]