# School Notices Constants
# ========================

# Notice Priority
NOTICE_PRIORITY_LOW = "low"
NOTICE_PRIORITY_MEDIUM = "medium"
NOTICE_PRIORITY_HIGH = "high"
NOTICE_PRIORITY_URGENT = "urgent"

NOTICE_PRIORITIES = [
    NOTICE_PRIORITY_LOW,
    NOTICE_PRIORITY_MEDIUM,
    NOTICE_PRIORITY_HIGH,
    NOTICE_PRIORITY_URGENT
]

# Notice Status
NOTICE_STATUS_DRAFT = "draft"
NOTICE_STATUS_PUBLISHED = "published"
NOTICE_STATUS_ARCHIVED = "archived"
NOTICE_STATUS_SCHEDULED = "scheduled"

NOTICE_STATUSES = [
    NOTICE_STATUS_DRAFT,
    NOTICE_STATUS_PUBLISHED,
    NOTICE_STATUS_ARCHIVED,
    NOTICE_STATUS_SCHEDULED
]

# Notice Category
NOTICE_CATEGORY_ACADEMIC = "academic"
NOTICE_CATEGORY_ADMINISTRATIVE = "administrative"
NOTICE_CATEGORY_EVENT = "event"
NOTICE_CATEGORY_EXAM = "exam"
NOTICE_CATEGORY_FEE = "fee"
NOTICE_CATEGORY_GENERAL = "general"

NOTICE_CATEGORIES = [
    NOTICE_CATEGORY_ACADEMIC,
    NOTICE_CATEGORY_ADMINISTRATIVE,
    NOTICE_CATEGORY_EVENT,
    NOTICE_CATEGORY_EXAM,
    NOTICE_CATEGORY_FEE,
    NOTICE_CATEGORY_GENERAL
]

# Notice Target
NOTICE_TARGET_ALL = "all"
NOTICE_TARGET_STUDENTS = "students"
NOTICE_TARGET_TEACHERS = "teachers"
NOTICE_TARGET_PARENTS = "parents"
NOTICE_TARGET_STAFF = "staff"

NOTICE_TARGETS = [
    NOTICE_TARGET_ALL,
    NOTICE_TARGET_STUDENTS,
    NOTICE_TARGET_TEACHERS,
    NOTICE_TARGET_PARENTS,
    NOTICE_TARGET_STAFF
]


__all__ = [
    "NOTICE_PRIORITIES",
    "NOTICE_PRIORITY_LOW",
    "NOTICE_PRIORITY_MEDIUM",
    "NOTICE_PRIORITY_HIGH",
    "NOTICE_PRIORITY_URGENT",
    "NOTICE_STATUSES",
    "NOTICE_STATUS_DRAFT",
    "NOTICE_STATUS_PUBLISHED",
    "NOTICE_STATUS_ARCHIVED",
    "NOTICE_STATUS_SCHEDULED",
    "NOTICE_CATEGORIES",
    "NOTICE_CATEGORY_ACADEMIC",
    "NOTICE_CATEGORY_ADMINISTRATIVE",
    "NOTICE_CATEGORY_EVENT",
    "NOTICE_CATEGORY_EXAM",
    "NOTICE_CATEGORY_FEE",
    "NOTICE_CATEGORY_GENERAL",
    "NOTICE_TARGETS",
    "NOTICE_TARGET_ALL",
    "NOTICE_TARGET_STUDENTS",
    "NOTICE_TARGET_TEACHERS",
    "NOTICE_TARGET_PARENTS",
    "NOTICE_TARGET_STAFF"
]