# School Courses Constants
# ======================

# Course Status
COURSE_STATUS_DRAFT = "draft"
COURSE_STATUS_PUBLISHED = "published"
COURSE_STATUS_ARCHIVED = "archived"
COURSE_STATUS_PENDING = "pending"

COURSE_STATUSES = [
    COURSE_STATUS_DRAFT,
    COURSE_STATUS_PUBLISHED,
    COURSE_STATUS_ARCHIVED,
    COURSE_STATUS_PENDING
]

# Course Type
COURSE_TYPE_CORE = "core"
COURSE_TYPE_ELECTIVE = "elective"
COURSE_TYPE_OPTIONAL = "optional"

COURSE_TYPES = [
    COURSE_TYPE_CORE,
    COURSE_TYPE_ELECTIVE,
    COURSE_TYPE_OPTIONAL
]

# Grading System
GRADING_SYSTEM_LETTER = "letter"
GRADING_SYSTEM_PERCENTAGE = "percentage"
GRADING_SYSTEM_GPA = "gpa"

GRADING_SYSTEMS = [
    GRADING_SYSTEM_LETTER,
    GRADING_SYSTEM_PERCENTAGE,
    GRADING_SYSTEM_GPA
]

# Enrollment Status
ENROLLMENT_STATUS_PENDING = "pending"
ENROLLMENT_STATUS_APPROVED = "approved"
ENROLLMENT_STATUS_REJECTED = "rejected"
ENROLLMENT_STATUS_DROPPED = "dropped"

ENROLLMENT_STATUSES = [
    ENROLLMENT_STATUS_PENDING,
    ENROLLMENT_STATUS_APPROVED,
    ENROLLMENT_STATUS_REJECTED,
    ENROLLMENT_STATUS_DROPPED
]

# Credit Hours
MIN_CREDIT_HOURS = 1
MAX_CREDIT_HOURS = 6
DEFAULT_CREDIT_HOURS = 3


__all__ = [
    "COURSE_STATUSES",
    "COURSE_STATUS_DRAFT",
    "COURSE_STATUS_PUBLISHED",
    "COURSE_STATUS_ARCHIVED",
    "COURSE_STATUS_PENDING",
    "COURSE_TYPES",
    "COURSE_TYPE_CORE",
    "COURSE_TYPE_ELECTIVE",
    "COURSE_TYPE_OPTIONAL",
    "GRADING_SYSTEMS",
    "GRADING_SYSTEM_LETTER",
    "GRADING_SYSTEM_PERCENTAGE",
    "GRADING_SYSTEM_GPA",
    "ENROLLMENT_STATUSES",
    "ENROLLMENT_STATUS_PENDING",
    "ENROLLMENT_STATUS_APPROVED",
    "ENROLLMENT_STATUS_REJECTED",
    "ENROLLMENT_STATUS_DROPPED",
    "MIN_CREDIT_HOURS",
    "MAX_CREDIT_HOURS",
    "DEFAULT_CREDIT_HOURS"
]