# School Grades Constants
# ====================

# Grade Letter
GRADE_A_PLUS = "A+"
GRADE_A = "A"
GRADE_A_MINUS = "A-"
GRADE_B_PLUS = "B+"
GRADE_B = "B"
GRADE_B_MINUS = "B-"
GRADE_C_PLUS = "C+"
GRADE_C = "C"
GRADE_C_MINUS = "C-"
GRADE_D_PLUS = "D+"
GRADE_D = "D"
GRADE_F = "F"

GRADE_LETTERS = [
    GRADE_A_PLUS, GRADE_A, GRADE_A_MINUS,
    GRADE_B_PLUS, GRADE_B, GRADE_B_MINUS,
    GRADE_C_PLUS, GRADE_C, GRADE_C_MINUS,
    GRADE_D_PLUS, GRADE_D, GRADE_F
]

# Grade Points
GRADE_POINTS = {
    GRADE_A_PLUS: 4.0, GRADE_A: 4.0, GRADE_A_MINUS: 3.7,
    GRADE_B_PLUS: 3.3, GRADE_B: 3.0, GRADE_B_MINUS: 2.7,
    GRADE_C_PLUS: 2.3, GRADE_C: 2.0, GRADE_C_MINUS: 1.7,
    GRADE_D_PLUS: 1.3, GRADE_D: 1.0, GRADE_F: 0.0
}

# Grade Status
GRADE_STATUS_DRAFT = "draft"
GRADE_STATUS_PUBLISHED = "published"
GRADE_STATUS_FINAL = "final"
GRADE_STATUS_ARCHIVED = "archived"

GRADE_STATUSES = [
    GRADE_STATUS_DRAFT,
    GRADE_STATUS_PUBLISHED,
    GRADE_STATUS_FINAL,
    GRADE_STATUS_ARCHIVED
]

# Assessment Type
ASSESSMENT_HOMEWORK = "homework"
ASSESSMENT_QUIZ = "quiz"
ASSESSMENT_MIDTERM = "midterm"
ASSESSMENT_FINAL = "final"
ASSESSMENT_PROJECT = "project"
ASSESSMENT_ASSIGNMENT = "assignment"

ASSESSMENT_TYPES = [
    ASSESSMENT_HOMEWORK,
    ASSESSMENT_QUIZ,
    ASSESSMENT_MIDTERM,
    ASSESSMENT_FINAL,
    ASSESSMENT_PROJECT,
    ASSESSMENT_ASSIGNMENT
]

# Weight Ranges
MIN_WEIGHT = 0
MAX_WEIGHT = 100


__all__ = [
    "GRADE_LETTERS",
    "GRADE_POINTS",
    "GRADE_STATUSES",
    "GRADE_STATUS_DRAFT",
    "GRADE_STATUS_PUBLISHED",
    "GRADE_STATUS_FINAL",
    "GRADE_STATUS_ARCHIVED",
    "ASSESSMENT_TYPES",
    "ASSESSMENT_HOMEWORK",
    "ASSESSMENT_QUIZ",
    "ASSESSMENT_MIDTERM",
    "ASSESSMENT_FINAL",
    "ASSESSMENT_PROJECT",
    "ASSESSMENT_ASSIGNMENT",
    "MIN_WEIGHT",
    "MAX_WEIGHT"
]